version: '3.9'
services:

  frontend:
    image: interstellarkai/apt200-frontend
    depends_on:
      - backend
      - socket
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    image: interstellarkai/apt200-backend
    ports:
      - "3001:3001"
    env_file: ./backend/.env
    networks:
      - app-network

  socket:
    image: interstellarkai/apt200-socket
    ports:
      - "8800:8800"
    env_file: ./frontend/.env
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
