version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: apt200-backend
#    container_name: myapp-node-server
    command: npm run start
    volumes:
      - ./backend/:/usr/app/backend/
      - /usr/app/backend/node_modules
    ports:
      - "3001:3001"
    #    depends_on:back
    #      - mongo
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    image: apt200-socket
    #    container_name: myapp-react-client
    command: npm run start
    volumes:
      - ./socket/:/usr/app/socket/
      - /usr/app/socket/node_modules
    depends_on:
      - frontend
    ports:
      - "8800:8800"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: apt200-frontend
#    container_name: myapp-react-client
    command: npm run start
    volumes:
      - ./frontend/:/usr/app/frontend/
      - /usr/app/frontend/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
