//use VSC Rest client for this

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username":"note with user",
    "name": "APT20000",
    "password":"APT20000"
}

###

GET http://localhost:3001/api/users

###

PUT http://localhost:3001/api/users/630dffe54627d7b52a26e7bd
Content-Type: application/json

{
    //"username":"lolololol"
    //"name": "Oregano2009",
    "password":"t8439g3454"
}
###

DELETE http://localhost:3001/api/users/630ddd797e83c063b81286ac