# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# https://stackoverflow.com/questions/61766177/react-with-node-js-in-aws-connection-between-react-and-node-issue
name: CD Docker Hub

on:
  workflow_run:
    workflows: [CI Testing]
    branches: [main]
    strategy: wait-all
    timeout: 5m
    types:
      - completed

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./frontend
          tags: interstellarkai/apt200-frontend:latest
          dockerfile: ./Dockerfile

      - name: Build and push backend image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./backend
          tags: interstellarkai/apt200-backend:latest
          dockerfile: ./Dockerfile

      - name: Build and push socket image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./socket
          tags: interstellarkai/apt200-socket:latest
          dockerfile: ./Dockerfile