# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Create env file
        working-directory: ./backend
        run: |
          touch .env
          echo MONGODB_CONNECTION=${{ secrets.MONGODB_CONNECTION }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo JWTKEY=${{ secrets.JWTKEY }} >> .env

      - name: CI Test
        working-directory: ./backend
        run: |
          npm ci
          npm test

    env:
      CI: true