# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Testing + CI Build + CD Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # mongodb-version: ['5.x']

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # - name: Start MongoDB
    #     uses: supercharge/mongodb-github-action@1.7.0
    #     with:
    #       mongodb-version: ${{ matrix.mongodb-version }}
    - run: |
        cd backend &&
        npm ci &&
        npm test
    env: 
      CI: true


      
